resources:
  - url: http://127.0.0.1:5000/uv-index-card.js
    type: module
views:
  - cards:
      - type: custom:uv-index-card
        name: UV Index Card Development
        entity: sun.sun
        test_gui: true
